import turtle

turtle.setup(1000, 1000)
turtle.showturtle()
turtle.speed(10)
turtle.pensize(3)
turtle.pencolor("red")
turtle.fillcolor("black")
turtle.begin_fill()
turtle.setheading(45)
turtle.forward(100)
turtle.setheading(-45)
turtle.forward(100)
turtle.setheading(-135)
turtle.forward(100)
turtle.setheading(-225)
turtle.forward(100)
turtle.forward(100)
turtle.setheading(-135)
turtle.forward(100)
turtle.setheading(-45)
turtle.forward(100)
turtle.setheading(45)
turtle.forward(100)
turtle.end_fill()
turtle.reset()

turtle.speed(8)
turtle.pensize(2)
turtle.pencolor("black")
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.goto(90, 0)
turtle.goto(-90, 0)
turtle.goto(0, 100)
turtle.penup()
turtle.goto(0, 45)
turtle.fillcolor("purple")
turtle.begin_fill()
turtle.pendown()
turtle.goto(90, 0)
turtle.goto(-90, 0)
turtle.goto(0, 45)
turtle.end_fill()
turtle.reset()

turtle.speed(7)
turtle.pensize(2)
turtle.pencolor('purple')
# Первый квадрат
turtle.goto(200, 0)
turtle.goto(200, -200)
turtle.goto(0, -200)
turtle.goto(0, 0)
# Второй квадрат
turtle.goto(0, 200)
turtle.goto(-200, 200)
turtle.goto(-200, 0)
turtle.goto(0, 0)
# Диагонали
turtle.goto(200, -200)
turtle.goto(-200, 200)
# Ребра
turtle.goto(0, 200)
turtle.goto(200, 0)
turtle.goto(-200, 0)
turtle.goto(0, -200)
turtle.reset()

turtle.speed(10)
turtle.pensize(3)
turtle.circle(50)
turtle.penup()
turtle.goto(150, 0)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-150, 0)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-75, -40)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(75, -40)
turtle.pendown()
turtle.circle(50)
turtle.reset()

turtle.speed(10)
turtle.pensize(2)
turtle.goto(200, 0)
turtle.write('Восток')
turtle.goto(-200, 0)
turtle.write('Запад')
turtle.goto(0, 0)
turtle.goto(0, 200)
turtle.write('Север')
turtle.goto(0, -200)
turtle.write('Юг')
turtle.goto(0, 0)
turtle.goto(0, -50)
turtle.circle(50)
turtle.reset()

turtle.speed(10)
turtle.dot()
turtle.goto(100, 100)
turtle.dot()
turtle.goto(100, -100)
turtle.dot()
turtle.goto(-100, 100)
turtle.dot()
turtle.goto(-100, -100)
turtle.dot()
turtle.goto(100, 100)
turtle.dot()
turtle.left(-180)
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown() 
turtle.goto(-100, -100)
turtle.right(180)
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.forward(20)
turtle.pendown() 
turtle.done()
