name = input("Введите ваше имя ")
adress = input("Введите ваш адресс ")
numer = input("Введите ваш номер ")
scool_cpec = input("Введите вашу специальность в учебном заведении ")
print(f"Имя: {name}\nАдресс: {adress}\nНомер: {numer}\nСпецальность: {scool_cpec:>5}")
